<template>
  <v-container class="grey lighten-10">
    <v-col
      class="mb-4"
      no-gutters
    >
      <v-row md="6">
        <v-card
          class="pa-10"
          outlined
          tile
        >
          <v-btn icon>
            <v-icon>mdi-magnify</v-icon>
            me
          </v-btn>

        </v-card>
      </v-row>
      <v-row
        md="4"
        offset-md="4"
      >
        <v-card
          class="pa-2"
          outlined
          tile
        >
            <v-btn icon>
              <v-icon>mdi-dots-vertical</v-icon>
              is
            </v-btn>

        </v-card>
      </v-row>
    </v-col>
  
    <v-row
      class="mb-6"
      no-gutters
    >
      <v-col
        md="3"
        offset-md="3"
      >
        <v-card
          class="pa-2"
          outlined
          tile
        >
          .Awsomista
        </v-card>
      </v-col>
      <v-col
        md="3"
        offset-md="-1"
      >
        <v-card
          class="pa-2"
          outlined
          tile
        >
          .is
        </v-card>
      </v-col>
    </v-row>
    <v-row no-gutters>
      <v-col
        md="6"
        offset-md="3"
      >
        <v-card
          class="pa-2"
          outlined
          tile
        >
          .desu
        </v-card>
      </v-col>
    </v-row>

    <v-row
      class="mb-6"
      no-gutters
    >
      <v-col
        md="7"
        offset-md="5"
      >
        <v-card
          class="pa-7"
          outlined
          tile
        >
          .and
        </v-card>
      </v-col>
      <v-col
        md="4"
        offset-md="9"
      >
        <v-card
          class="pa-2"
          outlined
          tile
        >
          .moreover
        </v-card>
      </v-col>
    </v-row>
    <v-col no-gutters>
      <v-row
        md="6"
        offset-md="3"
      >
        <v-card
          class="pa-10"
          outlined
          tile
        >
          .sassy
        </v-card>
      </v-row>
    </v-col>
  </v-container>
</template>